include:
  - project: 'ComFort/embedded/devops/ci-templates'
    ref: develop        # или нужная ветка/тег
    file: '/cpp-basic-pipeline.yml'

# при необходимости можно переопределить переменные/образ
variables:
  CMAKE_BUILD_TYPE: "Release"

default:
  tags: [ubuntu24_embedded]