name: Project CI

on:
  push:
    branches: [ main, develop, testing ]
  pull_request:
  workflow_dispatch:

jobs:
  call-shared-ci:
    uses: org/gha-templates/.github/workflows/cmake-conan-ci.yml@v1   # <— твой репозиторий/тег
    with:
      # метки раннера (можно заменить на '["ubuntu-latest"]' если SaaS раннеры)
      runner_labels_json: '["self-hosted","Linux","X64"]'

      cmake_build_type: Release
      conan_remote_name: insitech
      pkg_name: protolib                     # ← ИМЯ ПАКЕТА ДЛЯ CONAN

      # включаем/выключаем стадии под проект
      do_build_target: true
      do_tests: true
      do_coverage: true
      do_conan_publish: false               # включай только на релизных ветках при желании
      do_semantic_release: false

      # при необходимости — флаги
      extra_cmake_flags_x86: ""
      extra_build_flags_x86: ""
      extra_cmake_flags_arm: ""
      extra_build_flags_arm: ""

    secrets:
      CONAN_REMOTE_URL: ${{ secrets.CONAN_REMOTE_URL }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
